### PR TITLE
Award Emoji API

### PR DESCRIPTION
**Pull request by akkee**
Methods to deal with the [Award Emoji API](http://docs.gitlab.com/ce/api/award_emoji.html)
  * `award_emojis`: gets list of emojis for an awardable
  * `note_award_emojis`: gets list of emojis for a note on an awardable
  * `award_emoji`: gets a single emoji on an awardable
  * `note_award_emoji`: gets a single emoji for a note on an awardable
  * `create_award_emoji`: creates an emoji for an awardable
  * `create_note_award_emoji`: creates an emoji for a note on an awardable
  * `delete_award_emoji`: deletes an emoji from an awardable
  * `delete_note_award_emoji`: deletes an emoji from a note on an awardable

### CODE REVIEW

**Comment by akkee** [comment]
changes? requests?

**Comment by asedge** [comment]
You've been busy with the PRs too!  Thanks! 👍

**Comment by akkee** [comment]
@asedge yeah ;) When are we having a new release on rubygems ?

**Comment by asedge** [comment]
"Soon"? 😄

**Pull request merged**
