### PR TITLE
Add board api support

### PR DESCRIPTION
**Pull request by hlidotbe**
See https://docs.gitlab.com/ce/api/boards.html for documentation

### CODE REVIEW

**Comment by asedge** [comment]
@hlidotbe This looks good but it needs spec tests to be merged.

**Comment by hlidotbe** [comment]
Yes indeed, I hurried this a bit to be able to use it on my project and forgot to add the tests. Will do that ASAP.

**Comment by asedge** [comment]
@hlidotbe Ping me when you push the tests up.  Thanks!

**Comment by hlidotbe** [comment]
@asedge sorry, I forgot it. Here they are.

**Comment by hlidotbe** [comment]
If you'd rather prefer I rebase the three commits into one that can be done. Just let me know

**Comment by asedge** [comment]
@hlidotbe Thanks for the code!  I can squash the commits right from the PR.

**Pull request merged**
