### PR TITLE
Merge trains endpoint

### PR DESCRIPTION
**Pull request by andrcuns**
Adds support for merge train endpoints: https://docs.gitlab.com/ee/api/merge_trains.html

### CODE REVIEW

**Comment by floh96** [comment]
@andrcuns  could you reopen this pr?
@NARKOZ could you reopen and review this pr please?

**Comment by andrcuns** [comment]
@floh96 I think only maintainer can re-open pr. I can only create a new one from the same branch as far as I can tell

**Comment by floh96** [comment]
@andrcuns ok could you open a new PR? Would be sad if this gets lost

**Review by NARKOZ — APPROVED** [review]

**Comment by NARKOZ** [comment]
Thank you ❤️

**Pull request merged**
