### PR TITLE
Release v4.12.0

### PR DESCRIPTION
**Pull request by jasonwbarnett**

### CODE REVIEW

**Comment by jasonwbarnett** [comment]
@NARKOZ Hello! Anyway you could release a new version this week?

**Comment by jasonwbarnett** [comment]
@NARKOZ It's been 23 days since I originally requested this. Can you give me a realistic ETA for you to release this next version?

**Comment by NARKOZ** [comment]
Sorry for the delay! Just pushed version 4.12.0 to Rubygems.

**Comment by baurmatt** [comment]
Hey, thanks for the new version! :) Could you please update CHANGELOG/Release Page with the new feature/bugfixes?

**Pull request closed without merging**
