### PR TITLE
Add project_search method

### PR DESCRIPTION
**Pull request by ey3ball**
There is currently no way to search for a project, add a project_search method based on gitlab's /project/search API

### CODE REVIEW

**Comment by asedge** [comment]
Thanks for this PR, but I don't think this method is necessary.  You can already do searches using the `projects` method.  Have a look at this closed issue for some more details: #105.  If I remember correctly it also searches more than just the project name (project path, namespace and description).

**Comment by ey3ball** [comment]
This way of doing things does not work with older gitlab versions, for instance on my server (gitlab 7.6.2) :

$ gitlab projects "{search: 'test'}"
Will return all projects and does not filter.

Digging further it seems this facility was only added very recently in gitlab 7.7.0

See : https://github.com/gitlabhq/gitlabhq/commit/8689ce1efef8438debeec2a3a6d669f4d5a435c4 (Jan. 12, 2015 !)

Moreover, I think that whenever there is a REST API in gitlab it makes sense to have the corresponding command in this project for the sake of consistency / completeness.

What do you think ?

Thanks,

Florian

**Comment by asedge** [comment]
I'll reopen it and ping @NARKOZ for comment.

It would need tests to be merged but you may want to wait to hear back first.

**Comment by NARKOZ** [comment]
@asedge @ey3ball makes sense to add it.

@ey3ball could you also add tests?

**Comment by ey3ball** [comment]
Ok, I'l look into yet and update the PR

**Comment by StephenOTT** [comment]
:+1:  The `projects` command seems to be inconstant in its delivery of results.  Plus it seems to focus only on repos you own.

**Comment by asedge** [comment]
I wrote some tests for this so I merged it.  Thanks!

**Comment by StephenOTT** [comment]
GREAT!!! Thanks. This will make GitLab-Time-Tracking much easier to build :)

**Pull request merged**
