### PR TITLE
added username parameter to user

### PR DESCRIPTION
**Pull request by vincenzodibiaggio**
with accordingly of the gitlab-api docs I have added the username parameter to the user endpoint

https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md

### CODE REVIEW

**Comment by NARKOZ** [comment]
Thank you for your PR! 

However it's a breaking change. See #62 #89
I'll accept it if you implement it in non-breaking way.

**Comment by vincenzodibiaggio** [comment]
Ok, look if it's good for you. 
Thanks

**Comment by vincenzodibiaggio** [comment]
Also added delete method

**Comment by NARKOZ** [comment]
I meant to add `username` param, but implement it a way that doesn't break existing behaviour. 

For example: check if the last argument is Hash or String.

**Comment by lyio** [comment]
Also, as mentioned in #105 you can simply search by username with
```ruby
Gitlab.users(search: 'user_name')
```

**Comment by NARKOZ** [comment]
Implemented in #133

**Pull request closed without merging**
