### PR TITLE
Feature/230 note that project id can also be a string

### LINKED ISSUE #230: Note that project ID can also be a string
You can pass the project name as a string rather than the ID as an integer to access a project via the API, e.g. `https://gitlab.com/api/v3/projects/gitlab-org%2Fgitlab-ce/issues?private_token=PRIVATE_TOKEN`. This makes everything a lot easier to work with, also note the slash must be encoded for this to work. 

A lot of the gem's docs have to be updated with this.

See also https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/6102 and https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/6133.

### PR DESCRIPTION
**Pull request by bergholdt**
Make it possible to use NAMESPACE/PROJECT_NAME on all methods that uses project ID

ex.
  gitlab project gitlab-org/gitlab-ce
  gitlab milestones gitlab-org/gitlab-ce
  gitlab tree gitlab-org/gitlab-ce
  gitlab tags gitlab-org/gitlab-ce
  ...

Closes #230

### CODE REVIEW

**Comment by agimenez** [comment]
It is pretty needed :)

**Comment by asedge** [comment]
This is already possible if you url encode your project string before using it as a parameter to one of the methods.

I am not fond of adding code where documentation would do.  @jvanbaarsen - I know you're busy but do you have an opinion here?

**Comment by bergholdt** [comment]
Egen using CLI we should not expect users to url encode

**Comment by asedge** [comment]
Good point.  Have you written any tests that verify this functionality? I don't remember seeing any.

**Comment by bergholdt** [comment]
@asedge I have added specs to verify that project string is url_encoded.

Also made code change to support backword compatibility for users that already have url_encoded.

**Comment by bergholdt** [comment]
Note to self - always run all specs locally before push.

Removed the backward compatibility code again...as it was not that compatible 😊

**Comment by asedge** [comment]
Thanks!

**Comment by orta** [comment]
Any chance we can get a gem release with this in?

**Comment by asedge** [comment]
@orta Yes, "soon".  Trying to button a few things up first.

**Comment by asedge** [comment]
@orta `4.0.0` has been released.

**Pull request merged**
