### PR TITLE
Attempt to fix code climate failures

### PR DESCRIPTION
**Pull request by bwillis**
When making a PR, the code climate rubocop step fails with this error:
```
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:122:in `require': cannot load such file -- rubocop-performance (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:122:in `require'
	from /usr/local/bundle/gems/rubocop-0.52.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
```

It looks like it's related to the Ruby 2.5 upgrade (421d37d3e49ccfd78b842b5155aed2562b0f749c). The suggested fix (see https://github.com/codeclimate/codeclimate-rubocop/issues/165) is to remove the require from .rubocop.yml, so let's try that.

### CODE REVIEW

**Comment by bwillis** [comment]
After playing with this a bit, I realize that don't need codeclimate to run rubocop (and rubocop-performance) since it's part of the "CI / Rubocop lint" step. Additionally, when I tried to disable the rubocop check in `.codeclimate.yml` file I added, it doesn't seem to respect it. Based on these weird issues and this banner in codeclimate:
Screen Shot 2020-04-22 at 5 26 09 PM

I'm guessing there's something in codeclimate that has to be reconfigured. @NARKOZ does this make sense to you?

**Comment by NARKOZ** [comment]
I have intentionally disabled codeclimate 28 days ago 6599897. Don't know why it is still showing in status checks.

**Comment by NARKOZ** [comment]
> Don't know why it is still showing in status checks.

It seems now it is gone
Screen Shot 2020-04-23 at 06 58 35

Thank you.

**Comment by bwillis** [comment]
Cool thanks for resolving that !

**Pull request closed without merging**
