### PR TITLE
Allow adding of ssh keys for different users

### PR DESCRIPTION
**Pull request by formorer**
Hi, 

this is a fix for #313 that allows adding ssh keys for other users.

### CODE REVIEW

**Comment by asedge** [comment]
There are a couple problems here.
1) You've added a function (username_search) that's unrelated to the topic of this PR.  This is generally frowned upon, you really should file a separate PR for this function.
2) There are no tests added for new code paths.

**Comment by timofonic** [comment]
@formorer Are you still interested in improving this pull request so it can get merged?

@AAraKKe  @NARKOZ @cvand @asedge What about this?

**Comment by formorer** [comment]
I should look more often into my notifications, yes I am still interested we need that feature for Debians gitlab instance.

**Comment by NARKOZ** [comment]
@formorer please fix the issues that @asedge had mentioned. I'll merge after that.

**Comment by NARKOZ** [comment]
#413

**Pull request closed without merging**
