### PR TITLE
Add support for nested arrays on ObjectifiedHash

### PR DESCRIPTION
**Pull request by fabio-gallonetto**
At the moment ObjectifiedHash is missing out on hierarchies of objects where there are hashes contained within an array. Which is annoying as it happens in a lot of API calls.

This just adds an extra step to the initialiser of ObjectifiedHash so that arrays of hashes are handled properly

### CODE REVIEW

**Comment by NARKOZ** [comment]
Thank you. Could you add a test for this change?

**Comment by fabio-gallonetto** [comment]
Done!

**Comment by NARKOZ** [comment]
Tests are failing 😢

**Comment by fabio-gallonetto** [comment]
Something was wrong with GitHub today.. I closed the PR by mistake and can't open it again :(

**Comment by NARKOZ** [comment]
Unfortunately no, the reopen button is disabled for me. Recreating a new PR shouldn't be a problem though.

**Pull request closed without merging**
