### PR TITLE
Remove the Ruby 1.x support in the gemspec

### PR DESCRIPTION
**Pull request by orta**
This is the result from the discussion in https://github.com/NARKOZ/gitlab/issues/217 👍

### CODE REVIEW

**Comment by connorshea** [comment]
LGTM 👍

**Comment by jvanbaarsen** [comment]
Maybe we should also include this requirement in the README somewhere? (To prevent bug reports for users on older rubies)

**Comment by orta** [comment]
> Might want to add this to the Changelog though.

hah, I know just the tool for that ;)

**Comment by orta** [comment]
👍 done both

**Comment by asedge** [comment]
@orta Squash commits please.

**Comment by orta** [comment]
I shall, but if that's something you care about, you can do this as a part of the merge button rather than asking contributors to do it:

screen shot 2016-09-27 at 10 13 52

**Comment by orta** [comment]
👍 done

**Comment by asedge** [comment]
Thanks, I suppose I forgot that existed.

**Pull request merged**
