### PR TITLE
fix for issue 312: no method error with http party response

### PR DESCRIPTION
**Pull request by cvand**

### CODE REVIEW

**Comment by logicminds** [comment]
Can you fix your commit message so the ticket will auto close

`Fixes #312 - no method error with http party response`

**Comment by NARKOZ** [comment]
Thank you.

**Comment by born4new** [comment]
@NARKOZ Could you please release a new version on rubygems with that fix? It's quite a nasty one, as we cannot really do proper error handling with that issue...Thanks!

**Comment by NARKOZ** [comment]
@born4new Hi! Gitlab 4.3.0 should be out. Enjoy! ☺️

**Pull request merged**
