### PR TITLE
Add star_project and unstar_project methods.

### LINKED ISSUE #228: Add star/unstar methods for projects
Add `star_project` and `unstar_project` methods for `projects.rb`.

- `star_project`
  - http://docs.gitlab.com/ce/api/projects.html#star-a-project
  - `POST /projects/:id/star`
- `unstar_project`
  - http://docs.gitlab.com/ce/api/projects.html#unstar-a-project
  - `DELETE /projects/:id/star`

### PR DESCRIPTION
**Pull request by connorshea**
Fixes #228.

https://docs.gitlab.com/ce/api/projects.html#star-a-project
https://docs.gitlab.com/ce/api/projects.html#unstar-a-project

### CODE REVIEW

**Comment by connorshea** [comment]
Tests passing now 👍

**Comment by asedge** [comment]
Changelog & rebase?  Might as well take advantage of me having a few minutes 😃

**Comment by connorshea** [comment]
Changelog and rebased :)

**Comment by asedge** [comment]
Thanks!

**Pull request merged**
